lyx-tester: error out early if poly bu dir exists
This suggests something is not in sync. e.g., archived the TL24
polyglossia and then tried to archive the TL25 polyglossia to the
same location.

diff --git a/development/lyx-tester/switches b/development/lyx-tester/switches
--- a/development/lyx-tester/switches
+++ b/development/lyx-tester/switches
@@ -34,6 +34,10 @@ function switch-polyglossia-to-dev ()
     return 0
   else
     # TODO: need to account for different TL versions.
+    if [ -e "${polyglossia_tl_bu_d}" ]; then
+      echo "ERROR: The polyglossia backup dir already exists: ${polyglossia_tl_bu_d}" >&2
+      return 1
+    fi
     sudo mv "${polyglossia_tl_d}" "${polyglossia_tl_bu_d}"
     # We use a link to poly-dev. That is, we do not copy the directory. That
     # way, we can just do a git pull.
